"""Repository layer for MusicCtrl's SQLite index."""

from .library_repository import (
    AssetRecord,
    AssetUpsert,
    IndexBatchItem,
    IndexBatchRecord,
    LibraryRepository,
    RecordNotFoundError,
    RenameOperationItemRecord,
    RenameOperationRecord,
    RenamePlanItem,
    RepositoryClosedError,
    RepositoryCommitOutcomeUnknown,
    RepositoryDataError,
    RepositoryError,
    RepositoryPathError,
    RepositoryThreadError,
    ScanItemInput,
    ScanItemRecord,
    ScanReconcileResult,
    ScanSessionRecord,
    SettingRecord,
)

__all__ = [
    "AssetRecord",
    "AssetUpsert",
    "IndexBatchItem",
    "IndexBatchRecord",
    "LibraryRepository",
    "RecordNotFoundError",
    "RenameOperationItemRecord",
    "RenameOperationRecord",
    "RenamePlanItem",
    "RepositoryClosedError",
    "RepositoryCommitOutcomeUnknown",
    "RepositoryDataError",
    "RepositoryError",
    "RepositoryPathError",
    "RepositoryThreadError",
    "ScanItemInput",
    "ScanItemRecord",
    "ScanReconcileResult",
    "ScanSessionRecord",
    "SettingRecord",
]
